apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: danielmeixnerkspipelines 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: danielmeixnerkspipelines 
    spec:
      containers:
        - name: danielmeixnerkspipelines 
          image: dmxcr.azurecr.io/danielmeixnerkspipelines 
          ports:
          - containerPort: 3000